Use cloud events envelope
RedHatInsights/chrome-service-backend pull request #147
Opened 2023-05-23 12:46 UTC by Hyperkid123

Part of: https://issues.redhat.com/browse/RHCLOUD-26019

2023-05-25 17:48 UTC, BlakeHolifield requested changes
Short feedback and small details

2023-05-25 17:48 UTC, BlakeHolifield commented on rest/featureflags/featureflags.go
> +	fmt.Println(cfg)
Do you still need this?

2023-05-25 17:48 UTC, BlakeHolifield commented on rest/cloudEvents/cloudEvents.go
> +package cloudEvents
I think the standard is no mixed case for go, so `cloudevents` would be fine

2023-05-26 07:24 UTC, Hyperkid123 commented on rest/featureflags/featureflags.go
> +	fmt.Println(cfg)
Nope

2023-05-26 13:19 UTC, BlakeHolifield approved these changes

2023-05-29 07:11 UTC, merged