[RHCLOUD-26017] [Chrome service] Add navigation file unique ID validation
RedHatInsights/chrome-service-backend pull request #148
Opened 2023-05-23 21:21 UTC by rsun19

Added validation to make sure that no id's are repeated. It has already detected a duplicate in the itless folder. Let me know if the code needs to be cleaner, or if you don't want the program to throw an exception if a duplicate is found!

It uses recursion to access the nested ids in the json file.

2023-05-23 21:37 UTC, rsun19 commented
I think that checks fail because the program panics() when duplicates are found

2023-05-24 07:08 UTC, Hyperkid123 requested changes
You are correct about the CI failure

```
23:22:48 #13 1.236 panic: The id rhel in /src/chrome-service-backend/static/beta/prod/navigation/insights-navigation.json is not valid because it is duplicated
23:22:48 #13 1.236 
23:22:48 #13 1.236 
```

We should change the ID(s). I'll let you know the value(s).

2023-05-24 07:08 UTC, Hyperkid123 commented on cmd/validate/validateNavigation.go
> +		ok:= json.Unmarshal(fileContent, &data)
We should panic if there is a marshaling error. It does mean there is something wrong with the format.

2023-05-24 07:08 UTC, Hyperkid123 commented on cmd/validate/validateNavigation.go
> +
We should not skip the error check. Each block of code should have an escape hatch if it errors.

2023-05-24 07:08 UTC, Hyperkid123 commented on cmd/validate/validateNavigation.go
> +func checkForNestedItems(file string, navItem map[string]interface{}) {
The `checkForNestedItems` seems to be almost identical to the `parseJSONIDs`. The only difference are the nested items key. Can we merge these two functions into one?

Also, the two branches within the if statement are very similar, I think these can be extracted into a function.

2023-05-24 14:04 UTC, rsun19 commented
I made the code cleaner and added more error throwing.

There were some things I didn't catch from before. For example, there was a root nested inside an array: i.e. [{id: ...}]

That is handled now. This algorithm also assumes that group id does not need to be recorded.

2023-05-24 18:25 UTC, rsun19 commented
Made final commits, can now handle cases where the root is an array rather than a map. Code is way more concise.

2023-05-29 13:41 UTC, Hyperkid123 reviewed
@rsun19 OK. This looks better. We now have to deal with the duplicate `rhel` id.

We have to do the following:
- Rename `rhel` to `subs.rhel` onside all `insights-navigation.json` files. Do not change the top-level id. Only the id attribute in the subscriptions section.

Then we should be good.

2023-06-01 07:05 UTC, Hyperkid123 approved these changes

2023-06-01 07:05 UTC, merged